## Cleaning dataSet CSV (Revision)

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("messy_dataset .csv")

In [4]:
len(df)

372

In [6]:
df.head()

,Order ID,Customer Id,OrderDate,Ship Date,State,City,Sales Channel,Category,Sub Category,ProductID,Quantity,Unit Price,Discount %,TaxRate,ShippingCost,Order Total,Notes
0,ORD2263134,C934974,5/2/2025,5/8/2025,CA,sacramento,Phone,Clothing,hat,P32146,1.0,$841.84,0.00,0.065,12.99,909.55,Address corrected
1,ORD3302915,C682223,1/19/2026,1/25/2026,CO,colorado springs,Phone,Health,Protein,P49880,1.0,364.29,0.20,0.0825,$12.99,328.47,promo applied
2,ORD3194095,C484668,24-Nov-25,3-Dec-25,AZ,PHOENIX,IN-STORE,electronics,keyboard,P32860,2.0,$845.28,0.05,6.50%,4.99,"1,715.41",Address corrected
3,ORD7604726,C239994,12-Jul-25,16-Jul-25,NM,rio rancho,in-store,GROCERY,COFFEE,P58748,4.0,582.5,0.15,8.25%,$0.00,"2,143.89",NaN
4,ORD2703068,C959551,2/24/2026,2/28/2026,tx,houston,online,HEALTH,Protein,P89219,1.0,419.3,0.15,4.50%,$7.99,380.43,NaN

In [7]:
df.head(20)

,Order ID,Customer Id,OrderDate,Ship Date,State,City,Sales Channel,Category,Sub Category,ProductID,Quantity,Unit Price,Discount %,TaxRate,ShippingCost,Order Total,Notes
0,ORD2263134,C934974,5/2/2025,5/8/2025,CA,sacramento,Phone,Clothing,hat,P32146,1.0,$841.84,0.00,0.065,12.99,909.55,Address corrected
1,ORD3302915,C682223,1/19/2026,1/25/2026,CO,colorado springs,Phone,Health,Protein,P49880,1.0,364.29,0.20,0.0825,$12.99,328.47,promo applied
2,ORD3194095,C484668,24-Nov-25,3-Dec-25,AZ,PHOENIX,IN-STORE,electronics,keyboard,P32860,2.0,$845.28,0.05,6.50%,4.99,"1,715.41",Address corrected
3,ORD7604726,C239994,12-Jul-25,16-Jul-25,NM,rio rancho,in-store,GROCERY,COFFEE,P58748,4.0,582.5,0.15,8.25%,$0.00,"2,143.89",NaN
4,ORD2703068,C959551,2/24/2026,2/28/2026,tx,houston,online,HEALTH,Protein,P89219,1.0,419.3,0.15,4.50%,$7.99,380.43,NaN
5,ORD9202702,C875686,8/26/2025,8/26/2025,nm,rio rancho,In-Store,home,Air Purifier,P68652,1.0,$547.10USD,0.05,0.0825,7.99,570.61,Address corrected
6,ORD8021803,C587594,3/21/2025,3/31/2025,OK,tulsa,PHONE,Electronics,Headphones,P97853,2.0,413.11,0.00,0.065,$7.99,$887.91USD,NaN
7,ORD6121649,C842306,5-Aug-25,8/12/2025,UT,salt lake city,in-store,health,thermometer,P85100,4.0,757.58,0.00,0.0825,$0.00,"$3,280.32",NaN
8,ORD2550336,C889242,6/17/2025,6/18/2025,NM,Rio Rancho,Online,grocery,COFFEE,P60176,1.0,$70.31,0.00,0.0725,$12.99,$88.40,returned
9,ORD9429344,C013819,11/11/2025,11/16/2025,NM,Las Cruces,online,Health,Protein,P16606,-1.0,840.75,0.05,0.045,$4.99,-$829.66,updated record
10,ORD5818139,C137700,2/12/2025,2/13/2025,CA,Los Angeles,Phone,HEALTH,skincare,P19195,3.0,$448.88,0.00,0.045,$4.99USD,"$1,412.23",VIP customer
11,ORD6087966,C876007,2/26/2025,3/6/2025,CO,Boulder,IN-STORE,clothing,Jeans,P83248,2.0,115.28,0.00,0.065,$9.99,$255.54,returned
12,ORD7559665,C475144,3/2/2025,3/5/2025,CO,NaN,Online,GROCERY,pasta,P45334,3.0,$256.38,0.10,0.045,$9.99USD,733.37,NaN
13,ORD9312661,C113403,5/13/2025,5/18/2025,CA,San Diego,Online,HOME,Chair,P62650,5.0,$299.02,0.20,0.0825,$0.00,"$1,294.76",NaN
14,ORD7555716,C821952,8/5/2025,8/14/2025,UT,PROVO,IN-STORE,CLOTHING,Shoes,P30710,3.0,172.44,0.00,0.045,$7.99USD,$548.59,promo applied
15,ORD5033733,C294176,3/31/2025,4/1/2025,ut,SALT LAKE CITY,Online,home,VACUUM,P15573,4.0,$468.83,0.10,0.065,$4.99,"$1,802.48",returned
16,ORD3222355,C720532,2/4/2026,2/12/2026,NM,Las Cruces,ONLINE,home,BLENDER,P49570,-1.0,$290.34,0.00,0.0825,0,-$314.29,Address corrected
17,ORD4856923,C185863,5/21/2025,5/23/2025,AZ,mesa,In-Store,Electronics,monitor,P72567,2.0,$150.55,0.00,0.045,12.99,$327.64,Address corrected
18,ORD4436099,C003178,2/11/2026,2/16/2026,NM,albuquerque,In-Store,grocery,Pasta,P59213,5.0,637.92,0.05,0.045,$9.99,3176.47,NaN
19,ORD4608813,C351649,6/6/2025,6/16/2025,UT,Provo,phone,Electronics,Mouse,P40921,-1.0,44.44,0.05,0.065,$12.99,-31.97,NaN

## Inspecting Data

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 372 entries, 0 to 371
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       372 non-null    str
 1   Customer Id    372 non-null    str
 2   OrderDate      372 non-null    str
 3   Ship Date      372 non-null    str
 4   State          372 non-null    str
 5   City           358 non-null    str
 6   Sales Channel  372 non-null    str
 7   Category       372 non-null    str
 8   Sub Category   372 non-null    str
 9   ProductID      372 non-null    str
 10  Quantity       360 non-null    float64
 11  Unit Price     353 non-null    str
 12  Discount %     361 non-null    float64
 13  TaxRate        372 non-null    str
 14  ShippingCost   351 non-null    str
 15  Order Total    350 non-null    str
 16  Notes          240 non-null    str
dtypes: float64(2), str(15)
memory usage: 49.5 KB

## Cleaning Column names

In [9]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [10]:
df.head()

,order_id,customer_id,orderdate,ship_date,state,city,sales_channel,category,sub_category,productid,quantity,unit_price,discount_%,taxrate,shippingcost,order_total,notes
0,ORD2263134,C934974,5/2/2025,5/8/2025,CA,sacramento,Phone,Clothing,hat,P32146,1.0,$841.84,0.00,0.065,12.99,909.55,Address corrected
1,ORD3302915,C682223,1/19/2026,1/25/2026,CO,colorado springs,Phone,Health,Protein,P49880,1.0,364.29,0.20,0.0825,$12.99,328.47,promo applied
2,ORD3194095,C484668,24-Nov-25,3-Dec-25,AZ,PHOENIX,IN-STORE,electronics,keyboard,P32860,2.0,$845.28,0.05,6.50%,4.99,"1,715.41",Address corrected
3,ORD7604726,C239994,12-Jul-25,16-Jul-25,NM,rio rancho,in-store,GROCERY,COFFEE,P58748,4.0,582.5,0.15,8.25%,$0.00,"2,143.89",NaN
4,ORD2703068,C959551,2/24/2026,2/28/2026,tx,houston,online,HEALTH,Protein,P89219,1.0,419.3,0.15,4.50%,$7.99,380.43,NaN

## Fixing date Column

In [11]:
date_cols = ["orderdate","ship_date"]
for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors="coerce")

In [12]:
df.head()

,order_id,customer_id,orderdate,ship_date,state,city,sales_channel,category,sub_category,productid,quantity,unit_price,discount_%,taxrate,shippingcost,order_total,notes
0,ORD2263134,C934974,2025-05-02,2025-05-08,CA,sacramento,Phone,Clothing,hat,P32146,1.0,$841.84,0.00,0.065,12.99,909.55,Address corrected
1,ORD3302915,C682223,2026-01-19,2026-01-25,CO,colorado springs,Phone,Health,Protein,P49880,1.0,364.29,0.20,0.0825,$12.99,328.47,promo applied
2,ORD3194095,C484668,NaT,NaT,AZ,PHOENIX,IN-STORE,electronics,keyboard,P32860,2.0,$845.28,0.05,6.50%,4.99,"1,715.41",Address corrected
3,ORD7604726,C239994,NaT,NaT,NM,rio rancho,in-store,GROCERY,COFFEE,P58748,4.0,582.5,0.15,8.25%,$0.00,"2,143.89",NaN
4,ORD2703068,C959551,2026-02-24,2026-02-28,tx,houston,online,HEALTH,Protein,P89219,1.0,419.3,0.15,4.50%,$7.99,380.43,NaN

## Fixing Money Value

In [15]:
money_col = ["unit_price","shippingcost","order_total"]

for col in money_col:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace("$","")
        .str.replace("USD","")
        .str.strip()
        
    )
    df[col] = pd.to_numeric(df[col],errors="coerce")

In [16]:
df.head()

,order_id,customer_id,orderdate,ship_date,state,city,sales_channel,category,sub_category,productid,quantity,unit_price,discount_%,taxrate,shippingcost,order_total,notes
0,ORD2263134,C934974,2025-05-02,2025-05-08,CA,sacramento,Phone,Clothing,hat,P32146,1.0,841.84,0.00,0.065,12.99,909.55,Address corrected
1,ORD3302915,C682223,2026-01-19,2026-01-25,CO,colorado springs,Phone,Health,Protein,P49880,1.0,364.29,0.20,0.0825,12.99,328.47,promo applied
2,ORD3194095,C484668,NaT,NaT,AZ,PHOENIX,IN-STORE,electronics,keyboard,P32860,2.0,845.28,0.05,6.50%,4.99,NaN,Address corrected
3,ORD7604726,C239994,NaT,NaT,NM,rio rancho,in-store,GROCERY,COFFEE,P58748,4.0,582.50,0.15,8.25%,0.00,NaN,NaN
4,ORD2703068,C959551,2026-02-24,2026-02-28,tx,houston,online,HEALTH,Protein,P89219,1.0,419.30,0.15,4.50%,7.99,380.43,NaN

## Fixing percentage

In [17]:
df["taxrate"] =(
        df["taxrate"]
        .astype(str)
        .str.replace("%","")
) 
df["taxrate"] = pd.to_numeric(df["taxrate"],errors="coerce")
df.loc[df["taxrate"]>1,"taxrate"] =df["taxrate"]/100

In [18]:
df.head()

,order_id,customer_id,orderdate,ship_date,state,city,sales_channel,category,sub_category,productid,quantity,unit_price,discount_%,taxrate,shippingcost,order_total,notes
0,ORD2263134,C934974,2025-05-02,2025-05-08,CA,sacramento,Phone,Clothing,hat,P32146,1.0,841.84,0.00,0.0650,12.99,909.55,Address corrected
1,ORD3302915,C682223,2026-01-19,2026-01-25,CO,colorado springs,Phone,Health,Protein,P49880,1.0,364.29,0.20,0.0825,12.99,328.47,promo applied
2,ORD3194095,C484668,NaT,NaT,AZ,PHOENIX,IN-STORE,electronics,keyboard,P32860,2.0,845.28,0.05,0.0650,4.99,NaN,Address corrected
3,ORD7604726,C239994,NaT,NaT,NM,rio rancho,in-store,GROCERY,COFFEE,P58748,4.0,582.50,0.15,0.0825,0.00,NaN,NaN
4,ORD2703068,C959551,2026-02-24,2026-02-28,tx,houston,online,HEALTH,Protein,P89219,1.0,419.30,0.15,0.0450,7.99,380.43,NaN

In [19]:
df["quantity"] = pd.to_numeric(df["quantity"],errors="coerce")
df["quantity"] = df["quantity"].fillna(1)

## Handeling Missing Value

In [21]:
df.isna().sum()

order_id           0
customer_id        0
orderdate         58
ship_date         58
state              0
city              14
sales_channel      0
category           0
sub_category       0
productid          0
quantity           0
unit_price        19
discount_%        11
taxrate            0
shippingcost      21
order_total      101
notes            132
dtype: int64

## Removing Dupliacates

In [23]:
df.shape

(372, 17)

In [27]:
df = df.drop_duplicates()

In [28]:
df.shape

(366, 17)

## Final Inception

In [29]:
df.info()

<class 'pandas.DataFrame'>
Index: 366 entries, 0 to 371
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       366 non-null    str
 1   customer_id    366 non-null    str
 2   orderdate      310 non-null    datetime64[us]
 3   ship_date      309 non-null    datetime64[us]
 4   state          366 non-null    str
 5   city           354 non-null    str
 6   sales_channel  366 non-null    str
 7   category       366 non-null    str
 8   sub_category   366 non-null    str
 9   productid      366 non-null    str
 10  quantity       366 non-null    float64
 11  unit_price     347 non-null    float64
 12  discount_%     355 non-null    float64
 13  taxrate        366 non-null    float64
 14  shippingcost   346 non-null    float64
 15  order_total    265 non-null    float64
 16  notes          236 non-null    str
dtypes: datetime64[us](2), float64(6), str(9)
memory usage: 51.5 KB

In [30]:
df.head(20)

,order_id,customer_id,orderdate,ship_date,state,city,sales_channel,category,sub_category,productid,quantity,unit_price,discount_%,taxrate,shippingcost,order_total,notes
0,ORD2263134,C934974,2025-05-02,2025-05-08,CA,sacramento,Phone,Clothing,hat,P32146,1.0,841.84,0.00,0.0650,12.99,909.55,Address corrected
1,ORD3302915,C682223,2026-01-19,2026-01-25,CO,colorado springs,Phone,Health,Protein,P49880,1.0,364.29,0.20,0.0825,12.99,328.47,promo applied
2,ORD3194095,C484668,NaT,NaT,AZ,PHOENIX,IN-STORE,electronics,keyboard,P32860,2.0,845.28,0.05,0.0650,4.99,NaN,Address corrected
3,ORD7604726,C239994,NaT,NaT,NM,rio rancho,in-store,GROCERY,COFFEE,P58748,4.0,582.50,0.15,0.0825,0.00,NaN,NaN
4,ORD2703068,C959551,2026-02-24,2026-02-28,tx,houston,online,HEALTH,Protein,P89219,1.0,419.30,0.15,0.0450,7.99,380.43,NaN
5,ORD9202702,C875686,2025-08-26,2025-08-26,nm,rio rancho,In-Store,home,Air Purifier,P68652,1.0,547.10,0.05,0.0825,7.99,570.61,Address corrected
6,ORD8021803,C587594,2025-03-21,2025-03-31,OK,tulsa,PHONE,Electronics,Headphones,P97853,2.0,413.11,0.00,0.0650,7.99,887.91,NaN
7,ORD6121649,C842306,NaT,2025-08-12,UT,salt lake city,in-store,health,thermometer,P85100,4.0,757.58,0.00,0.0825,0.00,NaN,NaN
8,ORD2550336,C889242,2025-06-17,2025-06-18,NM,Rio Rancho,Online,grocery,COFFEE,P60176,1.0,70.31,0.00,0.0725,12.99,88.40,returned
9,ORD9429344,C013819,2025-11-11,2025-11-16,NM,Las Cruces,online,Health,Protein,P16606,-1.0,840.75,0.05,0.0450,4.99,-829.66,updated record
10,ORD5818139,C137700,2025-02-12,2025-02-13,CA,Los Angeles,Phone,HEALTH,skincare,P19195,3.0,448.88,0.00,0.0450,4.99,NaN,VIP customer
11,ORD6087966,C876007,2025-02-26,2025-03-06,CO,Boulder,IN-STORE,clothing,Jeans,P83248,2.0,115.28,0.00,0.0650,9.99,255.54,returned
12,ORD7559665,C475144,2025-03-02,2025-03-05,CO,NaN,Online,GROCERY,pasta,P45334,3.0,256.38,0.10,0.0450,9.99,733.37,NaN
13,ORD9312661,C113403,2025-05-13,2025-05-18,CA,San Diego,Online,HOME,Chair,P62650,5.0,299.02,0.20,0.0825,0.00,NaN,NaN
14,ORD7555716,C821952,2025-08-05,2025-08-14,UT,PROVO,IN-STORE,CLOTHING,Shoes,P30710,3.0,172.44,0.00,0.0450,7.99,548.59,promo applied
15,ORD5033733,C294176,2025-03-31,2025-04-01,ut,SALT LAKE CITY,Online,home,VACUUM,P15573,4.0,468.83,0.10,0.0650,4.99,NaN,returned
16,ORD3222355,C720532,2026-02-04,2026-02-12,NM,Las Cruces,ONLINE,home,BLENDER,P49570,-1.0,290.34,0.00,0.0825,0.00,-314.29,Address corrected
17,ORD4856923,C185863,2025-05-21,2025-05-23,AZ,mesa,In-Store,Electronics,monitor,P72567,2.0,150.55,0.00,0.0450,12.99,327.64,Address corrected
18,ORD4436099,C003178,2026-02-11,2026-02-16,NM,albuquerque,In-Store,grocery,Pasta,P59213,5.0,637.92,0.05,0.0450,9.99,3176.47,NaN
19,ORD4608813,C351649,2025-06-06,2025-06-16,UT,Provo,phone,Electronics,Mouse,P40921,-1.0,44.44,0.05,0.0650,12.99,-31.97,NaN

## Exporting clean Csv Files

In [32]:
df.to_csv("cleaned_dataset.csv", index=False)

In [33]:
df.describe()

,orderdate,ship_date,quantity,unit_price,discount_%,taxrate,shippingcost,order_total
count,310,309,366.000000,347.000000,355.000000,366.000000,346.000000,265.000000
mean,2025-07-22 13:14:19.354838,2025-07-30 11:06:24.466019,1.915301,423.601499,0.059718,0.066305,7.384942,490.606566
min,2025-01-02 00:00:00,2025-01-03 00:00:00,-1.000000,5.300000,0.000000,0.045000,0.000000,-911.930000
25%,2025-04-01 06:00:00,2025-04-19 00:00:00,1.000000,228.025000,0.000000,0.050000,4.990000,155.410000
50%,2025-07-16 00:00:00,2025-07-26 00:00:00,2.000000,401.000000,0.050000,0.065000,7.990000,406.980000
75%,2025-11-07 18:00:00,2025-11-08 00:00:00,3.000000,638.565000,0.100000,0.082500,9.990000,745.380000
max,2026-02-25 00:00:00,2026-03-04 00:00:00,5.000000,849.810000,0.200000,0.082500,12.990000,4048.860000
std,NaN,NaN,1.693157,243.812378,0.071386,0.013884,4.440570,696.669985

In [34]:
df.corr()

ValueError: could not convert string to float: 'ORD2263134'

In [35]:
df.tail()

,order_id,customer_id,orderdate,ship_date,state,city,sales_channel,category,sub_category,productid,quantity,unit_price,discount_%,taxrate,shippingcost,order_total,notes
367,ORD5832021,C933964,2025-03-17,2025-03-26,UT,Salt Lake City,In-Store,CLOTHING,t-shirt,P13294,-1.0,233.24,0.0,0.0725,0.00,-250.15,Address corrected
368,ORD5670801,C995025,2025-12-20,2025-12-20,NM,SANTA FE,phone,HEALTH,protein,P65958,1.0,300.28,0.0,0.0650,0.00,NaN,NaN
369,ORD1916614,C566465,2025-01-23,2025-01-23,CA,Los Angeles,In-Store,Home,BLENDER,P06974,-1.0,10.37,0.2,0.0825,9.99,1.01,expedite
370,ORD9644410,C218385,2025-04-02,2025-04-11,AZ,phoenix,In-Store,Home,lamp,P88742,2.0,178.60,0.2,0.0450,9.99,308.61,VIP customer
371,ORD8578243,C086458,2026-02-17,2026-02-18,ut,NaN,Phone,Grocery,snacks,P03654,2.0,715.54,0.2,0.0450,7.99,1204.37,returned

## Git check