In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("messy_dataset .csv")

In [4]:
len(df)

372

In [6]:
df.head()

,Order ID,Customer Id,OrderDate,Ship Date,State,City,Sales Channel,Category,Sub Category,ProductID,Quantity,Unit Price,Discount %,TaxRate,ShippingCost,Order Total,Notes
0,ORD2263134,C934974,5/2/2025,5/8/2025,CA,sacramento,Phone,Clothing,hat,P32146,1.0,$841.84,0.00,0.065,12.99,909.55,Address corrected
1,ORD3302915,C682223,1/19/2026,1/25/2026,CO,colorado springs,Phone,Health,Protein,P49880,1.0,364.29,0.20,0.0825,$12.99,328.47,promo applied
2,ORD3194095,C484668,24-Nov-25,3-Dec-25,AZ,PHOENIX,IN-STORE,electronics,keyboard,P32860,2.0,$845.28,0.05,6.50%,4.99,"1,715.41",Address corrected
3,ORD7604726,C239994,12-Jul-25,16-Jul-25,NM,rio rancho,in-store,GROCERY,COFFEE,P58748,4.0,582.5,0.15,8.25%,$0.00,"2,143.89",NaN
4,ORD2703068,C959551,2/24/2026,2/28/2026,tx,houston,online,HEALTH,Protein,P89219,1.0,419.3,0.15,4.50%,$7.99,380.43,NaN

In [7]:
df.head(20)

,Order ID,Customer Id,OrderDate,Ship Date,State,City,Sales Channel,Category,Sub Category,ProductID,Quantity,Unit Price,Discount %,TaxRate,ShippingCost,Order Total,Notes
0,ORD2263134,C934974,5/2/2025,5/8/2025,CA,sacramento,Phone,Clothing,hat,P32146,1.0,$841.84,0.00,0.065,12.99,909.55,Address corrected
1,ORD3302915,C682223,1/19/2026,1/25/2026,CO,colorado springs,Phone,Health,Protein,P49880,1.0,364.29,0.20,0.0825,$12.99,328.47,promo applied
2,ORD3194095,C484668,24-Nov-25,3-Dec-25,AZ,PHOENIX,IN-STORE,electronics,keyboard,P32860,2.0,$845.28,0.05,6.50%,4.99,"1,715.41",Address corrected
3,ORD7604726,C239994,12-Jul-25,16-Jul-25,NM,rio rancho,in-store,GROCERY,COFFEE,P58748,4.0,582.5,0.15,8.25%,$0.00,"2,143.89",NaN
4,ORD2703068,C959551,2/24/2026,2/28/2026,tx,houston,online,HEALTH,Protein,P89219,1.0,419.3,0.15,4.50%,$7.99,380.43,NaN
5,ORD9202702,C875686,8/26/2025,8/26/2025,nm,rio rancho,In-Store,home,Air Purifier,P68652,1.0,$547.10USD,0.05,0.0825,7.99,570.61,Address corrected
6,ORD8021803,C587594,3/21/2025,3/31/2025,OK,tulsa,PHONE,Electronics,Headphones,P97853,2.0,413.11,0.00,0.065,$7.99,$887.91USD,NaN
7,ORD6121649,C842306,5-Aug-25,8/12/2025,UT,salt lake city,in-store,health,thermometer,P85100,4.0,757.58,0.00,0.0825,$0.00,"$3,280.32",NaN
8,ORD2550336,C889242,6/17/2025,6/18/2025,NM,Rio Rancho,Online,grocery,COFFEE,P60176,1.0,$70.31,0.00,0.0725,$12.99,$88.40,returned
9,ORD9429344,C013819,11/11/2025,11/16/2025,NM,Las Cruces,online,Health,Protein,P16606,-1.0,840.75,0.05,0.045,$4.99,-$829.66,updated record
10,ORD5818139,C137700,2/12/2025,2/13/2025,CA,Los Angeles,Phone,HEALTH,skincare,P19195,3.0,$448.88,0.00,0.045,$4.99USD,"$1,412.23",VIP customer
11,ORD6087966,C876007,2/26/2025,3/6/2025,CO,Boulder,IN-STORE,clothing,Jeans,P83248,2.0,115.28,0.00,0.065,$9.99,$255.54,returned
12,ORD7559665,C475144,3/2/2025,3/5/2025,CO,NaN,Online,GROCERY,pasta,P45334,3.0,$256.38,0.10,0.045,$9.99USD,733.37,NaN
13,ORD9312661,C113403,5/13/2025,5/18/2025,CA,San Diego,Online,HOME,Chair,P62650,5.0,$299.02,0.20,0.0825,$0.00,"$1,294.76",NaN
14,ORD7555716,C821952,8/5/2025,8/14/2025,UT,PROVO,IN-STORE,CLOTHING,Shoes,P30710,3.0,172.44,0.00,0.045,$7.99USD,$548.59,promo applied
15,ORD5033733,C294176,3/31/2025,4/1/2025,ut,SALT LAKE CITY,Online,home,VACUUM,P15573,4.0,$468.83,0.10,0.065,$4.99,"$1,802.48",returned
16,ORD3222355,C720532,2/4/2026,2/12/2026,NM,Las Cruces,ONLINE,home,BLENDER,P49570,-1.0,$290.34,0.00,0.0825,0,-$314.29,Address corrected
17,ORD4856923,C185863,5/21/2025,5/23/2025,AZ,mesa,In-Store,Electronics,monitor,P72567,2.0,$150.55,0.00,0.045,12.99,$327.64,Address corrected
18,ORD4436099,C003178,2/11/2026,2/16/2026,NM,albuquerque,In-Store,grocery,Pasta,P59213,5.0,637.92,0.05,0.045,$9.99,3176.47,NaN
19,ORD4608813,C351649,6/6/2025,6/16/2025,UT,Provo,phone,Electronics,Mouse,P40921,-1.0,44.44,0.05,0.065,$12.99,-31.97,NaN